[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = ["npx drizzle-kit generate || true", "npm run build"]

[start]
cmd = "npm run start"
